### PR TITLE
Next complete editable actions templates

### PR DESCRIPTION
**Pull request by benabbon**
Edit and add new events

### CODE REVIEW

**Comment by benabbon** [comment]
@barraq Please merge this.

**Comment by barraq** [comment]
@benabbon this is merged in https://github.com/dahuapp/dahu/tree/next-final-demo. I'll have to correct few things before merging it to Next.

**Comment by benabbon** [comment]
Okey thank you.

**Comment by benabbon** [comment]
The next-final-demo is not working, I get this message !! 
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: 'undefined' is not an object (evaluating 'this.get("type").charAt')

**Pull request closed without merging**
