### PR TITLE
Add support for previews using unsupported browsing environments

### PR DESCRIPTION
**Pull request by RdNetwork**
This fixes the fact that the default browser didn't open when selecting
"Preview" on the menu (issue #138). A workaround was found for non-GNOME systems
where xdg-open is activated to manage default applications : this was
tested and verified to work on Debian Squeeze with KDE.

### CODE REVIEW

**Comment by barraq** [comment]
It would be nice to fix this bug for all platforms. Since opening a browser window is platform dependant, I suggest using the OSCheck helper (in editor/helper/OSCheck.java) and provide platform specific methods for opening the browser in the case `Desktop.isDesktopSupported()`is False.

If you refer to this thread http://stackoverflow.com/questions/5226212/how-to-open-the-default-webbrowser-using-java (I guess you used one of the answer) you can provide a generic approach for MacOS, Windows, and Linux.

Thanks

**Comment by RdNetwork** [comment]
As far as we tested, this was actually already working for other platforms (MacOS, Ubuntu and Windows were tested). The answers you linked seem quite similar to what was implemented in this fix, too. You mean that checks for OS should be added too ?

**Comment by barraq** [comment]
ok almost good, just could you avoid the creation of new File at every check ? Just put these files as object attributes. 

Also it would be nice to catch the case where nor Desktop nor ProcessBuilder("xdg-open", url) is supported in order to tell the user... Please add an issue about that (namely tell the user when his platform is not supported) and we will add it to the next sprint where we will add a Notifier module.

Thanks

**Comment by RdNetwork** [comment]
Thanks for the tip.
The corrections were made, do you still expect something more complete ?

**Comment by RdNetwork** [comment]
(Thanks for the tip)². I was more focused on the economy rather than the style, this solution is indeed more elegant and easy to edit and understand. This is now commited and pushed on my rep & PR.

**Comment by barraq** [comment]
ok, please rebase this PR to provide a single final commit.

**Comment by RdNetwork** [comment]
Done. I mostly kept the first 2 commits, since they are the most explanatory.

**Comment by barraq** [comment]
Almost good, please use Github keywords https://help.github.com/articles/closing-issues-via-commit-messages/ . In addition to these keywords use Addresses.
In this case, namely reword the commit: "Addresses #138" if it only addresses the issue and does not resolve it, otherwise reword it as "Fixes #138" if it does fix it.

**Comment by RdNetwork** [comment]
I reworded the title, thanks for the link.

**Comment by barraq** [comment]
Almost good... use present-tense, imperative-style for commit messages:

This fixes the fact that the default browser didn't open when selecting
"Preview" on the menu.  A workaround is found for non-GNOME systems
where xdg-open is activated to manage default applications: tested and 
verified to work on Debian Squeeze with KDE.
A verification for Linux system is added to make sure it is possible to
run xdg-open and get the default browser.

**Pull request merged**
